### ISSUE TITLE
Where is public folder?

### ISSUE THREAD

**Issue by sejin0104** [christmas-countdown/website#8]
I can’t use this source code, Because the public files not found

**Comment by eartharoid** [comment]
@sejin0104 do you have an error message?

**Comment by sejin0104** [comment]
Error: No Output Directory named "public" found after the Build completed. You can configure the Output Directory in your Project Settings.

**Comment by eartharoid** [comment]
It is configured to be built specifically for https://www.netlify.com/ and outputs to both `build` and `netlify/functions`.
If you want to host it on another platform or build static files that would typically go in a `public` directory (which will either not work or will omit the API), you'll need to reconfigure the SvelteKit adapter in `svelte.config.js`: https://kit.svelte.dev/docs/adapters.

**Comment by sejin0104** [comment]
thanx
